doorbell_api_encryption_key: "${DOORBELL_API_ENCRYPTION_KEY}"
doorbell_ota_password: "${DOORBELL_OTA_PASSWORD}"
rf_encryption_key: "${RF_ENCRYPTION_KEY}"
wifi_ssid: "YOUR_SSID"
wifi_password: "YOUR_PASSWORD"
doorbell_ap_password: "YOUR_AP_PASSWORD"
